// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh7WFnPRXGXmE72-rDS7Y0b2to4pUnO88',
    appId: '1:12331174892:web:765981a34c1028b1d9cec9',
    messagingSenderId: '12331174892',
    projectId: 'studymate-app-6033e',
    authDomain: 'studymate-app-6033e.firebaseapp.com',
    storageBucket: 'studymate-app-6033e.firebasestorage.app',
    measurementId: 'G-WW7YZ0DZGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKO7i0GuuphAHIztQan29IIF1xk-mus64',
    appId: '1:12331174892:android:ed022c9383427ce8d9cec9',
    messagingSenderId: '12331174892',
    projectId: 'studymate-app-6033e',
    storageBucket: 'studymate-app-6033e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImTYV_F2aBcOB6C3A7vrE6lbrNnfFndI',
    appId: '1:12331174892:ios:ad67aa36e13d8f96d9cec9',
    messagingSenderId: '12331174892',
    projectId: 'studymate-app-6033e',
    storageBucket: 'studymate-app-6033e.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImTYV_F2aBcOB6C3A7vrE6lbrNnfFndI',
    appId: '1:12331174892:ios:ad67aa36e13d8f96d9cec9',
    messagingSenderId: '12331174892',
    projectId: 'studymate-app-6033e',
    storageBucket: 'studymate-app-6033e.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh7WFnPRXGXmE72-rDS7Y0b2to4pUnO88',
    appId: '1:12331174892:web:115f6f095b15bb6ad9cec9',
    messagingSenderId: '12331174892',
    projectId: 'studymate-app-6033e',
    authDomain: 'studymate-app-6033e.firebaseapp.com',
    storageBucket: 'studymate-app-6033e.firebasestorage.app',
    measurementId: 'G-ZV9BBD1PPW',
  );

}